question_data = [
        {
         "question": "FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;",
         "correct_answer": "False",
        },
        {"category": "Geography", "type": "boolean", "difficulty": "medium",
                                          "question": "Vietnam is the only country in the world that starts with V. ",
                                          "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "In &quot;Team Fortress 2&quot;, the &quot;Bill&#039;s Hat&quot; is a reference to the game &quot;Dota 2&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "The French word to travel is &quot;Travail&quot;", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "History", "type": "boolean", "difficulty": "medium",
                                          "question": "In 1967, a magazine published a story about extracting hallucinogenic chemicals from bananas to raise moral questions about banning drugs.",
                                          "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "Android versions are named in alphabetical order.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "medium",
         "question": "&quot;Rich Uncle Pennybags&quot; from the board game &quot;Monopoly&quot; wears a monocle.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Cartoon & Animations", "type": "boolean", "difficulty": "medium",
         "question": "Snagglepuss was part of the Yogi Yahooies in the 1977 show Scooby&#039;s All-Star Laff-a-Lympics.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Sports", "type": "boolean", "difficulty": "medium",
         "question": "In 2008, Usain Bolt set the world record for the 100 meters with one shoelace untied.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Cartoon & Animations", "type": "boolean", "difficulty": "medium",
         "question": "In &quot;Avatar: The Last Airbender&quot; and &quot;The Legend of Korra&quot;, Lavabending is a specialized bending technique of Firebending.",
         "correct_answer": "False", "incorrect_answers": ["True"]}
    ]

